### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pranavpandey/dynamic-toasts#1]
Dear @pranavpandey 

I am trying to use this framework in order to create a toast error message,

```
                    DynamicToast.makeError(context, "Email or Password not valid").show();
```

but this is the error I got:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.vaevictis.myapplication, PID: 10187
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/pranavpandey/android/dynamic/utils/DynamicColorUtils;
                      at com.pranavpandey.android.dynamic.toasts.DynamicToast.makeError(DynamicToast.java:241)
                      at com.example.vaevictis.myapplication.user.UserController$1.onResponse(UserController.java:49)
                      at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6121)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pranavpandey.android.dynamic.utils.DynamicColorUtils" on path: DexPathList[[zip file "/data/app/com.example.vaevictis.myapplication-1/base.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.vaevictis.myapplication-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.vaevictis.myapplication-1/lib/arm64, /system/lib64, /vendor/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.pranavpandey.android.dynamic.toasts.DynamicToast.makeError(DynamicToast.java:241) 
                      at com.example.vaevictis.myapplication.user.UserController$1.onResponse(UserController.java:49) 
                      at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70) 
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6121) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 

```

Any clue of what can cause the problem?

**Comment by pranavpandey** [comment]
It is due to the concept of `api and implementation` which was introduced in Android studio 3.0. It will be fixed in the next release.

For a quick fix just add this also in your `build.gradle` file:
```groovy
dependencies {
    compile 'com.pranavpandey.android:dynamic-utils:0.6.0'
}
```

**Comment by FrancescoSaverioZuppichini** [comment]
This is my android studio's info

```
Android Studio 3.0
Build #AI-171.4408382, built on October 20, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1
```
I have that on my app.grandle

```
    compile 'com.pranavpandey.android:dynamic-toasts:0.6.0'
```
Other dependencies work fine, and I get no error while re-compile it.

Btw, thank you for your quick response ;)

**Comment by pranavpandey** [comment]
OK, Thanks! I will look into that.

This is for `dynamic-utils`. It should be included also.
```
compile 'com.pranavpandey.android:dynamic-utils:0.6.0'
```

**Comment by FrancescoSaverioZuppichini** [comment]
Adding that line results is a grandle error, 

```
Error:(32, 13) Failed to resolve: com.pranavpandey
```

**Comment by FrancescoSaverioZuppichini** [comment]
Okay I added

```
    compile 'com.pranavpandey.android:dynamic-utils:0.6.0'
```
And now it works :) You should upload the doc btw

**Comment by pranavpandey** [comment]
Thanks for the info!
Next version will fix this so, no need to add this separately.

**Comment by FrancescoSaverioZuppichini** [comment]
no problem :) Very cool toasts ;)

**Comment by pranavpandey** [comment]
Glad you like it. Issue has been fixed, just wait for the next release.
